name: Clean Aliyun Shares File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # 每天北京时间中午 12 点（UTC 4点）自动执行

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run Cleaning Script
        run: |
          python clean.py

      - name: Commit and Push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ali_shares.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-clean dead and expired ali_shares.txt [skip ci]" && git push)
